### ISSUE TITLE
Bug Report: https://docs.talawa.io/docs/talawa-mobile-docs/ on this site, the docs are visible as HTML tag.

### ISSUE THREAD

**Issue by IITI-tushar** [PalisadoesFoundation/talawa-docs#913] opened 2024-12-21 05:18 UTC
**Describe the bug**
On visiting this [site](https://docs.talawa.io/docs/talawa-mobile-docs/) docs are in HTML format.
![image](https://github.com/user-attachments/assets/e945b4b4-e9e6-4607-9565-ee4ee0eb402f)

**To Reproduce**

1.Go to the website - https://docs.talawa.io/docs/talawa-mobile-docs/  or go to Talawa-flutter-docs on the Talawa-Docs website.

**Expected behavior**
The format of the page should be like.
![image](https://github.com/user-attachments/assets/5eebd7d3-fb2c-4385-8358-17121c09f530)

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
![image](https://github.com/user-attachments/assets/8b56ccde-475e-4294-acd8-ac79601b6604)

**Screenshots**

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PAVANTEJ-05** [comment] 2024-12-21 15:12
I would like to work on this issue , it should be displaying in correct format
assign it to me.

**Comment by palisadoes** [comment] 2024-12-21 18:44
@IITI-tushar Is the issue caused by:

1. dart-docs not formatting the original markdown correctly in the talawa repo?
2. The merge cron job in this repo not updating the markdown correctly?

It doesn't make sense fixing this only to have a cron job overwrite the work

**Comment by jalajk3004** [comment] 2024-12-22 05:00
@palisadoes I would like to work on this issue. Please assign it to me.

**Comment by IITI-tushar** [comment] 2024-12-22 05:47
@palisadoes the issue is only with index.md file of Dart-docs.

**Comment by palisadoes** [comment] 2024-12-22 15:35
> @palisadoes the issue is only with index.md file of Dart-docs.

> @palisadoes the issue is only with index.md file of Dart-docs.

Thanks, but why? 

1. Is the error autogenerated, and if so how can we fix it?
2. Is the source dart file incorrect that is causing the error?

We should not be fixing an issue that will only be reappear with the next PR

**Comment by jalajk3004** [comment] 2024-12-22 17:04
@palisadoes 

1. Is the error autogenerated, and if so how can we fix it?

The errors in your HTML (escaped tags like \< and malformed URLs) are likely caused by improper handling in the source Dart file or an automated process generating the HTML. These issues often arise when escape characters are unnecessarily applied in strings or when dynamic URL generation misses adding proper prefixes like https://. If the Dart code uses raw strings or utility functions to escape HTML, it may be over-escaping characters or formatting URLs incorrectly, leading to invalid HTML.

2. Is the source dart file incorrect that is causing the error?

To fix this, review the Dart code responsible for generating the HTML. Ensure templates or string literals do not include unnecessary escape characters, and validate dynamic URL generation to include proper prefixes. Use debugging tools like print statements to compare the generated HTML with the expected output.

**Comment by IITI-tushar** [comment] 2024-12-22 18:55
@palisadoes, This error is with other files I have seen them.
I have checked commits on talawa-mobile-docs [commit- 2165505](https://github.com/PalisadoesFoundation/talawa-docs/commit/2165505cedd71ae111ba50098463a0dbf9a1ea0d) and concluded that [PR-873](https://github.com/PalisadoesFoundation/talawa-docs/pull/873) leads to those commits 
In this PR the changes in file lead to run a python script " talawa_api_md_mdx_format_adjuster.py " which may have converted md file syntax to mdx file syntax.
like this
![image](https://github.com/user-attachments/assets/8615731d-c2d0-4fcd-a306-45a25410049c)

TO

![image](https://github.com/user-attachments/assets/2151550c-8f60-4a45-ae16-46fbf540018c)

**Comment by palisadoes** [comment] 2024-12-22 22:19
1. The script worked previously without issue. It used to be only applied to the Typescript repos. It may not be appropriate for the Talawa repos. Is the script applied to all repos now?
2. There may be certain cases where the replacement is not valid. It should not be in all cases.
3. Can you identify them?

**Comment by IITI-tushar** [comment] 2024-12-23 14:04
@palisadoes,
Sir I have gone through the script. This type of script is present in all repos like {Talawa-mobile , Talawa-api , Talawa-admin}.  
In the scripts, this part is responsible for converting  < , > , { , } to their escape version like` \< , \> , \{  , \}` .


![image](https://github.com/user-attachments/assets/f10b5012-93ba-4975-b8a1-a07ad831616d)

So we are using docusaurus to render our md files in the website. And for the escaped tags like` \< , \> , \{  , \} `docusaurus renders them and display on the website as unescaped < , > , { , } .

for example,
this is the md file 
![image](https://github.com/user-attachments/assets/3590c00b-d632-4105-9d24-51e1a1f8d2e6)

on website it will be displayed as 
![image](https://github.com/user-attachments/assets/19fe7cf9-ede2-4325-8a7c-e13a8313d4d5)

have a look the escaped` \< , \>` changes to unescaped < , > .

But when we try to render an escaped HTML tag with like->   `  \<h1 id="talawa"\>Talawa\</h1\> `then it will display it as plain text like  `<h1 id="talawa">Talawa</h1> `  which is not supposed to be.

so to tackle this we can do this: 

When inside HTML tags (e.g., `<h1 id="talawa">Talawa</h1>`):
We do not escape the <, >, {, and } characters, because we want Docusaurus or the Markdown processor to interpret these characters as part of the HTML tags.
So, `<h1 id="talawa">Talawa</h1> `will remain as-is and render as a header on the website.

AND when Outside HTML tags (in normal text), we escape characters like <, >, {, and } to avoid any errors.

Example: "hi i < am < out> side" should become "hi i \< am \< out\> side", so the text renders as: "hi i < am < out> side".
Example 2: "hi I am outside `<and>`" if here i don't use escape then this will be the error:
![image](https://github.com/user-attachments/assets/cd91f4af-e1f5-46fe-8c9e-61cb575a21ad)

So in conclusion we need to use escape when only < , > are outside the html tag.

Am I thinking correct?

Please assign me this issue so i should start working on it.

And also there's a part of code in this script which removes " // ". That's why " // " in a link like : 
 " https://join.slack.com/t/thepalisadoes-dyb6419 " gets removed. so we have to work on that also.

**Comment by palisadoes** [comment] 2024-12-23 17:54
1. I fixed it by commenting out the line in the GitHub action. The script must not be run on markdown files generated with Dart-Docs. It is therefore not appropriate for flutter files.
2. The next step will be to remove the python script completely after we verify that the markdown generation is occurring as expected.

Thanks for identifying the issue. Closing.

**Closed as completed by palisadoes** 2024-12-23 17:54 UTC
Labels: bug, unapproved

**Comment by IITI-tushar** [comment] 2024-12-30 04:48
In the md_mdx_format_adjuster.py script we can do
>When inside HTML tags (e.g., <h1 id="talawa">Talawa</h1>):
>We do not escape the <, >, {, and } characters, because we want Docusaurus or the Markdown processor to interpret these 
    characters as part of the HTML tags.
>So, <h1 id="talawa">Talawa</h1> will remain as-is and render as a header on the website.

>AND when Outside HTML tags (in normal text), we escape characters like <, >, {, and } to avoid any errors.

check this comment also :https://github.com/PalisadoesFoundation/talawa-docs/issues/913#issuecomment-2559769934
@gautam-divyanshu  @palisadoes  This is the solution i am suggesting. If fine can I work on it??
If you have any other solution I can work on it also.

**Comment by IITI-tushar** [comment] 2024-12-30 04:50
> 1. I fixed it by commenting out the line in the GitHub action. The script must not be run on markdown files generated with Dart-Docs. It is therefore not appropriate for flutter files.
> 2. The next step will be to remove the python script completely after we verify that the markdown generation is occurring as expected.

@palisadoes sir after you comment out the script everything was fine.

**Comment by palisadoes** [comment] 2024-12-30 05:08
> > 1. I fixed it by commenting out the line in the GitHub action. The script must not be run on markdown files generated with Dart-Docs. It is therefore not appropriate for flutter files.
> > 2. The next step will be to remove the python script completely after we verify that the markdown generation is occurring as expected.
> 
> @palisadoes sir after you comment out the script everything was fine.

Please open an issue in Talawa to fix this. The Docusaurus site that is now part of that repo will need to process those files correctly.

Files in that repository's `talawa-mobile-docs/` directory will most likely move under `docs/` to more cleanly differentiate code and documentation

**Comment by IITI-tushar** [comment] 2024-12-30 05:14
OK sir,
so should just remove the part of code which escape the mdx character?
because it will fix the issue

**Comment by palisadoes** [comment] 2024-12-30 05:55
> OK sir, so should just remove the part of code which escape the mdx character? because it will fix the issue

Whatever fixes the issue
