### ISSUE TITLE
Updating footer on Talawa docs website 

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#407] opened 2023-03-09 16:17 UTC
**Is your feature request related to a problem? Please describe.**
the footer section of the Talawa project documentation website seems empty and has improper space utilization and does not look good it could be better in terms of listed content and list items 

**Describe the solution you'd like**
the footer content could either remove contact us or just have a contact column enlisting the contact means and there can be more columns enlisting the services and products offered and account section (like breezeCHM) as it looks more focused
![image_2023-03-09_214622398](https://user-images.githubusercontent.com/39475669/224085438-cc7aaa9a-f149-44c7-b6ef-775580ca8fe8.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NickGoko** [comment] 2023-03-09 16:20
can i work on this?

**Comment by SalilHarit** [comment] 2023-03-09 16:22
I would like to work on this.

**Comment by NickGoko** [comment] 2023-03-09 16:30
No problem nice catch still. Maybe we can collaborate on a future issue

**Comment by SalilHarit** [comment] 2023-03-09 16:32
sure would love to :D

**Comment by palisadoes** [comment] 2023-03-09 17:05
Please change the title so that everyone has a better understanding of what the issue is. We currently have 5 issues titled `Feature Request`

**Comment by Cioppolo14** [comment] 2023-03-09 18:03
@lonereaper Can you provide a screenshot of what your vision is?

**Comment by SalilHarit** [comment] 2023-03-09 18:37
![image_2023-03-10_000720889](https://user-images.githubusercontent.com/39475669/224123011-39c04944-56f0-43e7-8471-f9262c814fae.png)

**Comment by Cioppolo14** [comment] 2023-03-09 20:18
@lonereaper What would you link to for the items under News?

**Comment by SalilHarit** [comment] 2023-03-09 20:48
We can link newly added pages for each list item that would have to be created and maintained for example tracking major changes to the talawa for events we can link intern event dates and similarly for bug fixes we can link the recently fixed bugs from repository

**Comment by Cioppolo14** [comment] 2023-03-10 01:06
@lonereaper I really like these ideas, but I think we should save it for a part of a internship project. That way the pages can be done before the links. I am going to close it for now but please keep this in mind in the future.

**Closed as not planned** 2023-03-10 01:06 UTC
Labels: documentation, unapproved
