### ISSUE TITLE
Feature Request: Talawa Library List

### ISSUE THREAD

**Issue by Yass32** [PalisadoesFoundation/talawa-docs#405] opened 2023-03-09 14:28 UTC
**Is your feature request related to a problem? Please describe.**
I feel like there's no need to have a list of talawa libraries on the sidebar and in the main content again. its redundant

**Describe the solution you'd like**
I would like to remove the talawa libraries list from the main and keep the library list on the sidebar

![Screenshot (28)](https://user-images.githubusercontent.com/108995581/224054983-1cfe074a-bedd-4038-b929-4ecf3c164d3e.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment] 2023-03-09 14:35
@Yass32 You may not be aware, but this content is automatically generated with each PR from talawa-admin. Please research how to ensure your design will be maintained and not interfere with that process. @tasneemkoushar and @anwersayeed can provide details

**Comment by palisadoes** [comment] 2023-03-09 17:05
Please change the title so that everyone has a better understanding of what the issue is. We currently have 5 issues titled `Feature Request`

**Comment by Yass32** [comment] 2023-03-09 17:08
Okay no problem

**Comment by Cioppolo14** [comment] 2023-03-09 18:02
@Yass32 I have assigned you this item, please be sure to work with the people mentioned above. Thank you!

**Comment by Yass32** [comment] 2023-03-09 18:25
Okay thank you

**Comment by tasneemkoushar** [comment] 2023-03-11 05:01
> Okay thank you

You can try and read more about this [here](https://dart.dev/tools/dart-doc).

**Comment by Ladyperpetua** [comment] 2023-03-23 10:38
can i get assigned on it please

**Comment by tasneemkoushar** [comment] 2023-03-24 09:55
> can i get assigned on it please

We do not need this change for now.

**Comment by palisadoes** [comment] 2023-03-24 11:27
Closing

**Closed as not planned** 2023-03-24 11:27 UTC
