### ISSUE TITLE
Feature Request:- Api docs , Adding setup guide to setup the talawa-api locally

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#525] opened 2023-03-17 17:46 UTC
**Is your feature request related to a problem? Please describe.**
A setup guide for the Talawa api would be really helpful, it will contain on how to install the api and running it locally
such as something like an installation.md page

**Describe the solution you'd like**
This would require a thorough research and would need collaboration.

**Approach to be followed (optional)**
Researching on building the API locally
Jotting down the instruction in a manner thats easy to understand and follow
It will be made impeccable and in a way that we don't assume the reader has experience with tools being used currently

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to be assigned

**Comment by palisadoes** [comment] 2023-03-17 18:16
Thanks for considering this. This is a duplication of effort. The INSTALLATION.md file should be the sole source of truth for now. Any updates should be in that document. Closing.

**Comment by Biki-das** [comment] 2023-03-17 18:21
@palisadoes quite did not got what you mean by making the INSTALLATION.md file source of truth , there is no such page currently, I Have sort of think and made this below , this would just be a setup guide for the talawa api , does something like this exist already in our docs?

https://user-images.githubusercontent.com/72331432/225986981-b1f8862b-2def-46b8-b3ff-846d7ab9abd1.mp4

**Comment by palisadoes** [comment] 2023-03-17 18:30
It's documented here:

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md
- https://docs.talawa.io/docs/internships/outreachy/getting-starteds

This page needs to be removed.

**Comment by Biki-das** [comment] 2023-03-17 18:33
ah got you what you mean by the installation.md , thanks for the direction,@palisadoes since you opened it , should i work on this one, and document the installation,md here in our docs?

**Comment by palisadoes** [comment] 2023-03-17 18:35
The second link documents the fact that people can use the INSTALLATION.md file. We may want to move the second link to a more prominent location. Please coordinate with @Cioppolo14

**Comment by Biki-das** [comment] 2023-03-17 18:49
> The second link documents the fact that people can use the INSTALLATION.md file. We may want to move the second link to a more prominent location. Please coordinate with @Cioppolo14

sure!

**Comment by Cioppolo14** [comment] 2023-03-18 13:55
@biki-das Can you create a new issue for this? I think the issue is that we need a section on the talawa-docs website that gives direction, similar to https://docs.talawa.io/docs/internships/outreachy/getting-starteds. However, it should not have the details of the actual md files, as we only want to maintain one location.  But, this information is hard to find in the internship, outreachy area, so we need a better, more obviously location under About.  And we need to decide what to do with the Outreachy section. I'm going to close this for now. Thank you!

**Closed as not planned** 2023-03-18 14:10 UTC
Labels: unapproved

**Comment by Biki-das** [comment] 2023-03-19 07:03
yeah @Cioppolo14 sure let me figure it out!
