### ISSUE TITLE
Inconsistency in the theme of the Talawa Package Documentation Website

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#338] opened 2023-03-07 10:39 UTC
**Describe the bug**
1. The navigation bar should be presented as displayed in the expected behavior screenshot, attached below.
2. There is font inconsistency, according to the proposed theme, throughout the talawa package page.

**To Reproduce**

1. Add a navigation bar to the talawa package page to ease page navigation.
2. Improve the font consistency of the theme to enhance user readability of the docs.

**Expected behavior**
![contri1](https://user-images.githubusercontent.com/78542333/223396645-ab013b6b-4c0c-498c-bdd3-7f2e747ecf78.PNG)

**Actual behavior**
![issue1](https://user-images.githubusercontent.com/78542333/223396719-829a9384-4c20-4f14-9922-ec9bdaa988d0.PNG)

I would like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment] 2023-03-07 13:46
Good point, but we have an issue created for that already. Please coordinate with the person assigned this issue to see whether they may need assistance.
- https://github.com/PalisadoesFoundation/talawa-docs/issues/338

**Closed as completed by palisadoes** 2023-03-07 13:46 UTC
Labels: bug

**Comment by ishitakapoor26** [comment] 2023-03-07 14:37
I am not able to find the existing issue. Could you please tag the issue number? 
Thank you.

**Comment by palisadoes** [comment] 2023-03-07 14:39
1. It's in my comment above. The issue is asking that the look and feel is consistent in the generated HTML.
2. The HTML for those other areas is generated automatically with each pull request from `Talawa` and `Talawa-API`
