### ISSUE TITLE
Fix the consistency of text font and white spaces

### ISSUE THREAD

**Issue by elizabeth-agada** [PalisadoesFoundation/talawa-docs#397] opened 2023-03-09 06:21 UTC
As a first time contributor to this project and open source, i thought to start with something that is beginner friendly and that would improve the look and feel of the talawa docs

**Comment by elizabeth-agada** [comment] 2023-03-09 06:22
/home/elizabeth/Pictures/Screenshots/Screenshot from 2023-03-09 07-13-59.png

**Comment by RotimiDesire** [comment] 2023-03-09 12:32
**My idea of what the problem is:**
     i) The font family for the text doesn't complement the website's overall design.
     ii) The grid system used to design the the second section of the home page needs to be properly aligned and spaced.

**Proposed solution:**
    i) Making use of the free resource of google fonts, I can provide a better and more complementing font family
    ii) With CSS grid, there could be the implementation of attractive design while also sorting whitespace problem.

**Comment by RotimiDesire** [comment] 2023-03-09 12:32
I'd love to be assigned to this issue.

**Comment by Cioppolo14** [comment] 2023-03-09 13:28
@elizabeth-agada Can you post some screen shots of your idea please?

**Comment by Yass32** [comment] 2023-03-09 14:09
Hello @elizabeth-agada can we collaborate on this

**Comment by elizabeth-agada** [comment] 2023-03-09 14:30
Yes, we can do that.

**Comment by Cioppolo14** [comment] 2023-03-11 03:43
I am going to close this issue, as we have a home page redesign in issue #344. Thank you for your submission, please keep submitting your ideas!

**Closed as not planned by Cioppolo14** 2023-03-11 03:43 UTC
Labels: unapproved
