### ISSUE TITLE
Rendering Issue of the image

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#493] opened 2023-03-14 19:49 UTC
**Describe the bug**
The image of [Talawa Page](https://docs.talawa.io/talawa/index.html) is not able to get rendered.

**Expected behavior**
The desired image should be visible.

**Screenshots**
<img width="766" alt="image" src="https://user-images.githubusercontent.com/67657066/225119223-a37f7372-de47-4793-977f-f15c74bf651f.png">

**Comment by singhavs** [comment] 2023-03-14 19:51
@palisadoes can I work on this issue?

**Comment by iamatifmoin** [comment] 2023-03-15 08:09
@Cioppolo14 @palisadoes 
Duplicate of #404.

**Comment by evasharma12** [comment] 2023-03-15 10:34
@singhavs This issue has been resolved [here](https://github.com/PalisadoesFoundation/talawa-docs/issues/404).
Kindly look into other issues and keep contributing.

**Comment by Cioppolo14** [comment] 2023-03-15 12:10
Thank you for your submission.  This is already being address in #404, so I am going to close this for now.  Please, keep the ideas coming!

**Closed as not planned by Cioppolo14** 2023-03-15 12:10 UTC
Labels: bug, unapproved
